# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :centos_web1 do |web|
    web.vm.box = "centos64u"
    web.vm.network :private_network, ip: "192.168.33.16"
    web.vm.network "public_network", bridge: "enp5s0", ip: "192.168.131.32", netmask: "255.255.255.0"
    web.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_web1" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "web"
    end
  end

  config.vm.define :centos_web2 do |web2|
    web2.vm.box = "centos64u"
    web2.vm.network :private_network, ip: "192.168.33.17"
    web2.vm.network "public_network", bridge: "enp5s0", ip: "192.168.131.34", netmask: "255.255.255.0"
    web2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_web2" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "web2"
    end
  end

  config.vm.define :centos_db do |db|
    db.vm.box = "centos64u"
    db.vm.network :private_network, ip: "192.168.33.18"
    db.vm.network "public_network", bridge: "enp5s0", ip: "192.168.131.33", netmask: "255.255.255.0"
    db.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_db" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "db"
    end
  end

  config.vm.define :centos_balancer do |balancer|
    balancer.vm.box = "centos64u"
    balancer.vm.network :private_network, ip: "192.168.33.19"
    balancer.vm.network "public_network", bridge: "enp5s0", ip: "192.168.131.35", netmask: "255.255.255.0"
    balancer.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_balancer" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "balancer"
    end
  end
  
end
